---
- name: Ensure GPG is installed
  become: true
  ansible.builtin.apt:
    name:
      - gpg
- name: Fix Hashicorp repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb https://apt.releases.hashicorp.com {{ hashicorp_release }} stable
    filename: hashicorp
    state: absent
- name: Configure Hashicorp repository
  become: true
  deb822_repository:
    name: hashicorp
    types: deb
    uris: https://apt.releases.hashicorp.com
    suites: "{{ hashicorp_release }}"
    components: main
    signed_by: https://apt.releases.hashicorp.com/gpg
  environment:
    https_proxy: "{{ hashicorp_https_proxy | default('') }}"
